apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: Ym9vay1yZHMuY3lscWs4Y21nMWN2LnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==          # Decode the db host then enter here
  db_username: YWRtaW4=                                                                  # Decode the username then enter here
  db_password: c3JpdmFyZGhhbg==                                                          # Decode the password then enter here
