apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: ZGF0YWJhc2UtMS5jazkwMHVjeXlxaXYudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t          # Decode the db host then enter here
  db_username: YWRtaW4=                                                                  # Decode the username then enter here
  db_password: Q2xvdWQxMjM=                                                              # Decode the password then enter here
